export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'
export const POST_LIST_RESET = 'POST_LIST_RESET'

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST'
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS'
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL'

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST'
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS'
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL'
export const POST_UPDATE_RESET = 'POST_UPDATE_RESET'

export const  POST_DETAILS_SUCCESS = ' POST_DETAILS_SUCCESS'
export const  POST_DETAILS_REQUEST = ' POST_DETAILS_REQUEST'
export const  POST_DETAILS_FAIL = ' POST_DETAILS_FAIL'

export const POST_CREATE_SUCCESS ='POST_CREATE_SUCCESS'
export const POST_CREATE_REQUEST='POST_CREATE_REQUEST'
export const POST_CREATE_FAIL ='POST_CREATE_FAIL'
export const POST_CREATE_RESET = 'POST_CREATE_RESET'

export const POST_LIKE_REQUEST= 'POST_LIKE_REQUEST'
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS'
export const POST_LIKE_FAIL = 'POST_LIKE_FAIL'

export const POST_UNLIKE_REQUEST= 'POST_UNLIKE_REQUEST'
export const POST_UNLIKE_SUCCESS = 'POST_UNLIKE_SUCCESS'
export const POST_UNLIKE_FAIL = 'POST_UNLIKE_FAIL'

export const  ADD_COMMENT_REQUEST = ' ADD_COMMENT_REQUEST'
export const  ADD_COMMENT = ' ADD_COMMENT'

export const  ADD_COMMENT_FAIL = ' ADD_COMMENT_FAIL'

export const REMOVE_COMMENT_REQUEST = 'REMOVE_COMMENT_REQUEST'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'

export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'
